<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Confirmation;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;


/**
 * Class ConfirmationsRepository
 * @package EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmationsRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Confirmation::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

 /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('confirmation');
    }

    /**
     * Save entity.
     *
     * @param Confirmation confirmation Confirmation entity
     */
    public function save(Confirmation $confirmation)
    {
        $this->_em->persist($confirmation);
        $this->_em->flush();
    }

 /**
     * Delete entity.
     *
     * @param \AppBundle\Entity\Confirmation $confirmation Confirmation entity
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function delete(Confirmation $confirmation)
    {
        $this->_em->remove($confirmation);
        $this->_em->flush();
    }
}

