<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Operation;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;


/**
 * Class OperationsRepository
 * @package EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationsRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Operation::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

 /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function queryAll()
    {
        return $this->createQueryBuilder('operation');
    }

    /**
     * Save entity.
     *
     * @param Operation $operation Operation entity
     */
    public function save(Operation $operation)
    {
        $this->_em->persist($operation);
        $this->_em->flush();
    }

 /**
     * Delete entity.
     *
     * @param \AppBundle\Entity\Operation $operation Operation entity
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function delete(Operation $operation)
    {
        $this->_em->remove($operation);
        $this->_em->flush();
    }
}

